### ISSUE TITLE
Oak Saplings grow sacred trees. 

### ISSUE THREAD

**Issue by Aintence** [Migmag789/FanaticEngMarv#5]
Simple enough, instead of normal oak trees, huge ones grow and drop a lot of saplings/apples when harvested, it can cause issues if not controlled well.
![2018-11-17_17 21 31](https://user-images.githubusercontent.com/20612621/48871425-9862cd00-eddc-11e8-8144-32dd57fe6a6f.png)

**Comment by Migmag789** [comment]
I'll check that that evening ;)

**Comment by Migmag789** [comment]
Sorry, I didn't had time. I don't know what cause the thing, but I think that's because when you put 4 oak saplings next to each other, that spawn that huge thing. Do a line with 1 dirt block, one stone block, so saplings aren't connected each other.
